### ISSUE TITLE
Raw audio format

### ISSUE THREAD

**Issue by bcomerford** [SketchingDev/ivr-tester#55]
Is there a preferred audio player to listen to playback? The .raw format isn't recognized by any of my standard applications. Thanks!

**Comment by SketchingDev** [comment]
Personally I prefer to convert them to a wave file using [SoX](http://sox.sourceforge.net/). The wave file can then be opened in your audio player of choice:

```shell
sox -r 8000 -t raw -e u-law -c 1 -b 8 input.raw -t wav output.wav
```

Alternatively you can use [Audacity](https://www.audacityteam.org/):

1. File > Import > Raw Data...
2. Provide following in 'Import Raw Data' window
    * Encoding: U-Law
    * Byte-order: Little-endian
    * Channels: 1 Channel (Mono)
    * Start offset: 0
    * Amount to import: 100%
    * Sample Rate: 8000Hz
3. Import

Let me know if you have any problems with the above. I will make sure I add these instructions to the README as it's a good question!

**Comment by bcomerford** [comment]
Awesome, I downloaded `ocenaudio` and was toying around with the encoding but just plugged in the specs you provided and it works great!

**Comment by SketchingDev** [comment]
Splendid! Glad to hear it worked
